TPRACTICO/TPRACTICO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('USUARIO/', include ("USUARIO.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
]

TPRACTICO/USUARIO/urls.py
from django.urls import path
from . import views

app_name = 'USUARIO'
urlpatterns = [
    path('layout', views.layout, name='layout'),
    path('', views.home, name='home'),
    path('registro', views.registro, name="registro"),
    path('buscar', views.buscar, name="buscar"),
    path('categories', views.categories, name="categories"),
    path('contact', views.contact, name="contact"),
    path('about', views.about, name="about"),
    path('category1', views.category1, name="category1"),
    path('category2', views.category2, name="category2"),
    path('category3', views.category3, name="category3"),
    path('product1', views.product1, name="product1"),
    path('product2', views.product2, name="product2"),
    path('product3', views.product3, name="product3"),
    path('product4', views.product4, name="product4"),
    path('product5', views.product5, name="product5"),
    path('product6', views.product6, name="product6"),
    path('product7', views.product7, name="product7"),
    path('product8', views.product8, name="product8"),
    path('product9', views.product9, name="product9"),
    path('product10', views.product10, name="product10"),
]

TPRACTICO/USUARIO/models.py
from django.db import models

# Create your models here.

TPRACTICO/USUARIO/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistroForm(UserCreationForm):
    username = forms.CharField(
        label='Usuario', widget=forms.TextInput(attrs={'class': 'usuario'}), max_length=150, required=True, help_text='Requerido. 150 caracteres o menos. Letras, dígitos y @ /. / + / - / _ solamente.')
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Al menos 8 caracteres y no pueden ser todos numeros.')
    password2 = forms.CharField(
        label='Repetir Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Ingrese la misma contraseña que antes, para verificación.')
    first_name = forms.CharField(
        label='Nombre', widget=forms.TextInput(attrs={'class': 'nombre'}), max_length=30, required=False, help_text='Opcional.')
    last_name = forms.CharField(
        label='Apellido', widget=forms.TextInput(attrs={'class': 'apellido'}), max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(
        label='Email', widget=forms.TextInput(attrs={'class': 'email'}), max_length=254, required=True, help_text='Se requiere una direccion de email valida.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

TPRACTICO/USUARIO/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from .forms import *

def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()          
            return HttpResponseRedirect(reverse('login'))
    else:
        form = RegistroForm()
    return render(request, 'registration/registro.html', {
        'form': form
        })

def buscar(request):
    return render(request, 'buscar/search.html')

def layout(request):
    return render(request, 'registration/layout.html')

def home(request):
    return render(request, 'index/home.html')

def categories(request):
    return render(request, 'categorias/categories.html')
    
def contact(request):
    return render(request, 'index/contact.html')

def about(request):
    return render(request, 'index/about.html')

def category1(request):
    return render(request, 'categorias/category1.html')

def category2(request):
    return render(request, 'categorias/category2.html')

def category3(request):
    return render(request, 'categorias/category3.html')

def product1(request):
    return render(request, 'productos/product1.html')

def product2(request):
    return render(request, 'productos/product2.html')

def product3(request):
    return render(request, 'productos/product3.html')

def product4(request):
    return render(request, 'productos/product4.html')

def product5(request):
    return render(request, 'productos/product5.html')

def product6(request):
    return render(request, 'productos/product6.html')

def product7(request):
    return render(request, 'productos/product7.html')

def product8(request):
    return render(request, 'productos/product8.html')

def product9(request):
    return render(request, 'productos/product9.html')

def product10(request):
    return render(request, 'productos/product10.html')

TPRACTICO/USUARIO/templates/categorias/categories.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Categorias</title>
        <!--stylesheet-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/categories.css' %}">
        <!--fonts-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="header">
            <p>JAGUARETE KAA S.A.</p>
        </div>
        <div class="container">
            <nav class="nav-main">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="nav-brand">
                <ul class="nav-menu">
                    <li>
                        <a href="{% url 'USUARIO:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:categories' %}">Categorias</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:about' %}">Acerca de</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:contact' %}">Contacto</a>
                    </li>
                </ul>
                <ul class="nav-menu-right">
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'USUARIO:registro' %}">Registro</a>
                        <a href="{% url 'USUARIO:buscar' %}">
                            <i class="fa fa-search"></i>
                        </a>
                        <a title="carrito" href="shop.html"><img src="https://img.icons8.com/nolan/64/shopping-cart.png" alt="carrito"/></a>
                    </li>
                </ul>
            </nav>
            <hr>
            <!--products-cards-->
            <div class="categories-cards">
                <div class="cat1">
                    <img src="{% static 'img/cat1.jpg' %}" alt="Categoria 1">
                    <div>
                        <h3>Categoria 1</h3>
                        <a href="{% url 'USUARIO:category1' %}">More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                </div>
                <div class="cat2">
                    <img src="{% static 'img/cat2.jpg' %}" alt="Categoria 2">
                    <div>
                        <h3>Categoria 2</h3>
                        <a href="{% url 'USUARIO:category2' %}">More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                </div>
                <div class="cat3">
                    <img src="{% static 'img/cat3.jpg' %}" alt="Categoria 3">
                    <div>
                        <h3>Categoria 3</h3>
                        <a href="{% url 'USUARIO:category3' %}">More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
            <section class="social">
                <p>Follow JAGUARETE KAA</p>
                <div class="links">
                  <a href="https://facebook.com">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="https://twitter.com">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="https://linkdin.com">
                    <i class="fab fa-linkedin"></i>
                  </a>
                </div>
            </section>
        </div>
    </body>
</html>

TPRACTICO/USUARIO/templates/categorias/category1.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Categoria 1</title>
        <!--stylesheet-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/products.css' %}">
        <!--fonts-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="header">
            <p>JAGUARETE KAA S.A.</p>
        </div>
        <div class="container">
            <nav class="nav-main">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="nav-brand">
                <ul class="nav-menu">
                    <li>
                        <a href="{% url 'USUARIO:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:categories' %}">Categorias</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:about' %}">Acerca de</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:contact' %}">Contacto</a>
                    </li>
                </ul>
                <ul class="nav-menu-right">
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'USUARIO:registro' %}">Registro</a>
                        <a href="{% url 'USUARIO:buscar' %}">
                            <i class="fa fa-search"></i>
                        </a>
                        <a title="carrito" href="shop.html"><img src="https://img.icons8.com/nolan/64/shopping-cart.png" alt="carrito"/></a>
                    </li>
                </ul>
            </nav>
            <hr>
            <div class="cat1-products">
                <div class="cat1-product1">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product1' %}">Ukelele</a>
                        <p>El Ukelele es un instrumento musical de cuerda pulsada, similar a una guitarra de pequeño tamaño.</p>
                    </div>
                </div>
                <div class="cat1-product2">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product2' %}">Guitarra</a>
                        <p>Guitarras en cedro con la más alta calidad en fabricación y sonido. Bien elaboradas, detalladas, buenas terminaciones.</p>
                    </div>
                </div>
                <div class="cat1-product3">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product3' %}">Mouse</a>
                        <p>El Centrophorus se abre paso en el mercado demostrando que no es solo una cara bonita y una construcción sólida.</p>
                    </div>
                </div>
            </div>
            <section class="social">
                <p>Follow JAGUARETE KAA</p>
                <div class="links">
                  <a href="https://facebook.com">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="https://twitter.com">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="https://linkdin.com">
                    <i class="fab fa-linkedin"></i>
                  </a>
                </div>
            </section>
        </div>
    </body>
</html>

TPRACTICO/USUARIO/templates/categorias/category2.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Categoria 2</title>
        <!--stylesheet-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/products.css' %}">
        <!--fonts-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="header">
            <p>JAGUARETE KAA S.A.</p>
        </div>
        <div class="container">
            <nav class="nav-main">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="nav-brand">
                <ul class="nav-menu">
                    <li>
                        <a href="{% url 'USUARIO:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:categories' %}">Categorias</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:about' %}">Acerca de</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:contact' %}">Contacto</a>
                    </li>
                </ul>
                <ul class="nav-menu-right">
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'USUARIO:registro' %}">Registro</a>
                        <a href="{% url 'USUARIO:buscar' %}">
                            <i class="fa fa-search"></i>
                        </a>
                        <a title="carrito" href="shop.html"><img src="https://img.icons8.com/nolan/64/shopping-cart.png" alt="carrito"/></a>
                    </li>
                </ul>
            </nav>
            <hr>
            <div class="cat1-products">
                <div class="cat1-product1">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product4' %}">Longboard</a>
                        <p>Longboard Rimable La plataforma desplegable reduce el centro de gravedad para un mayor control.</p>
                    </div>
                </div>
                <div class="cat1-product2">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product5' %}">Libro: Reina Roja</a>
                        <p>Juan Gómez-Jurado. Primera edición.</p>
                    </div>
                </div>
                <div class="cat1-product3">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product6' %}">Libro: Loba Negra</a>
                        <p>Juan Gómez-Jurado. Segunda edición.</p>
                    </div>
                </div>
            </div>
            <section class="social">
                <p>Follow JAGUARETE KAA</p>
                <div class="links">
                  <a href="https://facebook.com">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="https://twitter.com">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="https://linkdin.com">
                    <i class="fab fa-linkedin"></i>
                  </a>
                </div>
            </section>
        </div>
    </body>
</html>

TPRACTICO/USUARIO/templates/categorias/category3.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Categoria 1</title>
        <!--stylesheet-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/products.css' %}">
        <!--fonts-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="header">
            <p>JAGUARETE KAA S.A.</p>
        </div>
        <div class="container">
            <nav class="nav-main">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="nav-brand">
                <ul class="nav-menu">
                    <li>
                        <a href="{% url 'USUARIO:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:categories' %}">Categorias</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:about' %}">Acerca de</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:contact' %}">Contacto</a>
                    </li>
                </ul>
                <ul class="nav-menu-right">
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'USUARIO:registro' %}">Registro</a>
                        <a href="{% url 'USUARIO:buscar' %}">
                            <i class="fa fa-search"></i>
                        </a>
                        <a title="carrito" href="shop.html"><img src="https://img.icons8.com/nolan/64/shopping-cart.png" alt="carrito"/></a>
                    </li>
                </ul>
            </nav>
            <hr>
            <div class="cat1-products">
                <div class="cat1-product1">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product7' %}">Libro: Rey Blanco</a>
                        <p>Juan Gómez-Jurado. Segunda edición.</p>
                    </div>
                </div>
                <div class="cat1-product2">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product8' %}">Samsung A30</a>
                        <p>El Samsung A30 Duos cuenta con el sistema operativo avanzado Android 9.0 Pie que aprende tus hábitos para adaptarse a tu rutina y lograr la máxima eficiencia de tu equipo.</p>
                    </div>
                </div>
                <div class="cat1-product3">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product9' %}">Memoria Kingston 64gb</a>
                        <p>DataTraveler es una unidad Flash USB ligera, el compacto diseño de esta unidad complementa cualquier dispositivo compatible.</p>
                    </div>
                </div>
                <div class="cat1-product4">
                    <div class="parc">
                        <a href="{% url 'USUARIO:product10' %}">Teclado</a>
                        <p>Ultra delgado teclado inalámbrico Bluetooth para IPAD/Iphone/Mac/ordenador portátil/PC de escritorio/tableta.</p>
                    </div>
                </div>
            </div>
            <section class="social">
                <p>Follow JAGUARETE KAA</p>
                <div class="links">
                  <a href="https://facebook.com">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="https://twitter.com">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="https://linkdin.com">
                    <i class="fab fa-linkedin"></i>
                  </a>
                </div>
            </section>
        </div>
    </body>
</html>

TPRACTICO/USUARIO/templates/index/home.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>JAGUARETE KAA</title>
        <!--stylesheet-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/styles.css'%}">
        <!--fonts-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="header">
            <p>JAGUARETE KAA S.A.</p>
        </div>
        <div class="container">
            <nav class="nav-main">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="nav-brand">
                <ul class="nav-menu">
                    <li>
                        <a href="{% url 'USUARIO:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:categories' %}">Categorias</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:about' %}">Acerca de</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:contact' %}">Contacto</a>
                    </li>
                </ul>
                <ul class="nav-menu-right">
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'USUARIO:registro' %}">Registro</a>
                        <a href="search.html">
                            <i class="fa fa-search"></i>
                        </a>
                        <a title="carrito" href="shop.html"><img src="https://img.icons8.com/nolan/64/shopping-cart.png" alt="carrito"/></a>
                    </li>
                </ul>
            </nav>
            <hr>
            <!--products-cards-->
            <div class="products-cards">
                <div>
                    <img src="{% static 'img/producto1.jpg' %}" alt="Producto 1">
                    <h3>Ukelele</h3>
                    <p>El Ukelele es un instrumento musical de cuerda pulsada, similar a una guitarra de pequeño tamaño.</p>
                    <a href="{% url 'USUARIO:product1' %}">Ver Producto<i class="fas fa-angle-double-right"></i></a>
                </div>
                <div>
                    <img src="{% static 'img/producto2.jpg' %}" alt="Producto 2">
                    <h3>Guitarra</h3>
                    <p>Guitarras en cedro con la más alta calidad en fabricación y sonido. Bien elaboradas, detalladas, buenas terminaciones.</p>
                    <a href="{% url 'USUARIO:product2' %}">Ver Producto<i class="fas fa-angle-double-right"></i></a>
                </div>
                <div>
                    <img src="{% static 'img/producto3.jpg' %}" alt="Producto 3">
                    <h3>Mouse</h3>
                    <p>El Centrophorus se abre paso en el mercado demostrando que no es solo una cara bonita y una construcción sólida.</p>
                    <a href="{% url 'USUARIO:product3' %}">Ver Producto<i class="fas fa-angle-double-right"></i></a>
                </div>
            </div>
            <!--showcase-->
            <header class="showcase">
                <div class="products-section">
                    <div>
                        <h2>Longboard</h2>
                        <p>Longboard Rimable La plataforma desplegable reduce el centro de gravedad para un mayor control.</p>
                        <a href="{% url 'USUARIO:product4' %}" class="btn">Read More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                    <div>
                        <h2>Libro: Reina Roja</h2>
                        <p>Juan Gómez-Jurado. Primera edición.</p>
                        <a href="{% url 'USUARIO:product5' %}" class="btn">Read More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                    <div>
                        <h2>Libro: Loba Negra</h2>
                        <p>Juan Gómez-Jurado. Segunda edición.</p>
                        <a href="{% url 'USUARIO:product6' %}" class="btn">Read More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                    <div>
                        <h2>Libro: Rey Blanco</h2>
                        <p>Juan Gómez-Jurado. Tercera edición.</p>
                        <a href="{% url 'USUARIO:product7' %}" class="btn">Read More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                    <div>
                        <h2>Samsung A30</h2>
                        <p>El Samsung A30 Duos cuenta con el sistema operativo avanzado Android 9.0 Pie que aprende tus hábitos para adaptarse a tu rutina y lograr la máxima eficiencia de tu equipo.</p>
                        <a href="{% url 'USUARIO:product8' %}" class="btn">Read More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                    <div>
                        <h2>Memoria Kingston 64gb</h2>
                        <p>DataTraveler es una unidad Flash USB ligera, el compacto diseño de esta unidad complementa cualquier dispositivo compatible.</p>
                        <a href="{% url 'USUARIO:product9' %}" class="btn">Read More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                    <div>
                        <h2>Teclado</h2>
                        <p>Ultra delgado teclado inalámbrico Bluetooth para IPAD/Iphone/Mac/ordenador portátil/PC de escritorio/tableta.</p>
                        <a href="{% url 'USUARIO:product10' %}" class="btn">Read More<i class="fas fa-angle-double-right"></i></a>
                    </div>
                </div>
            </header>
            <section class="social">
                <p>Follow JAGUARETE KAA</p>
                <div class="links">
                  <a href="https://facebook.com">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="https://twitter.com">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="https://linkdin.com">
                    <i class="fab fa-linkedin"></i>
                  </a>
                </div>
            </section>
        </div>
    </body>
</html>

TPRACTICO/USUARIO/templates/index/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registro</title>
        <!--stylesheet-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <!--fonts-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="header">
            <p>JAGUARETE KAA S.A.</p>
        </div>
        <div class="container">
            <nav class="nav-main">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="nav-brand">
                <ul class="nav-menu">
                    <li>
                        <a href="{% url 'USUARIO:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:categories' %}">Categorias</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:about' %}">Acerca de</a>
                    </li>
                    <li>
                        <a href="{% url 'USUARIO:contact' %}">Contacto</a>
                    </li>
                </ul>
                <ul class="nav-menu-right">
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'USUARIO:registro' %}">Registro</a>
                        <a href="{% url 'USUARIO:buscar' %}">
                            <i class="fa fa-search"></i>
                        </a>
                        <a title="carrito" href="shop.html"><img src="https://img.icons8.com/nolan/64/shopping-cart.png" alt="carrito"/></a>
                    </li>
                </ul>
            </nav>
            <hr>
            {% block content %}
            {% endblock %}
            <section class="social">
                <p>Follow JAGUARETE KAA</p>
                <div class="links">
                  <a href="https://facebook.com">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="https://twitter.com">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="https://linkedin.com">
                    <i class="fab fa-linkedin"></i>
                  </a>
                </div>
            </section>
        </div>
    </body>
</html>